# Generated by Django 3.0.4 on 2020-04-01 04:42

from django.db import migrations, models
import tweetme.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetme', '0003_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweetme.models.validate_content]),
        ),
    ]
